services:
  - type: web
    name: blog-ai-studio
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard.app_cloud:app
    envVars:
      - key: NOTION_API_KEY
        sync: false
      - key: NOTION_DATABASE_ID
        value: 9cd5aabbbbd644128abc34a58de7c2f2
      - key: PYTHON_VERSION
        value: "3.12"
